Changes
Changes

diff --git a/wirebotctl b/wirebotctl
--- a/wirebotctl
+++ b/wirebotctl
@@ -1,16 +1,10 @@
 #!/bin/sh
 
-# The path to your pid file
-PIDFILE="/opt/wired/wired.pid"
+PIDFILE="$HOME/.wirebot/wirebot.pid"
+CONFIGFILE="$HOME/.wirebot/config"
 
-# The path to your status file
-STATUSFILE="/opt/wired/wired.status"
-
-# The path to your wired binary
-WIRED="/opt/wired/wired"
-
-# Flags to pass to wired
-WIREDFLAGS="-D -d /opt/wired"
+# The path to your wirebot binary
+WIREBOT=$( SELF=$(dirname "$0") && bash -c "cd \"$SELF\" && pwd" )
 
 # Begin script
 PROG=$(basename $0)
@@ -34,7 +28,7 @@ checkrunning() {
 	checkpid
 
 	if [ $RUNNING -eq 0 ]; then
-		echo "$PROG: $CMD: wired is not running"
+		echo "$PROG: $CMD: wirebot is not running"
 		exit 1
 	fi
 }
@@ -44,24 +38,36 @@ case $CMD in
 		checkpid
 
 		if [ $RUNNING -eq 1 ]; then
-			echo "$PROG: $CMD: wired (pid $PID) already running"
+			echo "$PROG: $CMD: wirebot (pid $PID) already running"
 			exit 1
 		fi
 
-		if $WIRED $WIREDFLAGS; then
-			echo "$PROG: $CMD: wired started"
+		if screen -Sdm wirebot $WIREBOT/wirebot ; then
+			/bin/bash "$HOME/.wirebot/wirebot.sh" watcher_init
+			echo "$PROG: $CMD: wirebot started"
 		else
-			echo "$PROG: $CMD: wired could not be started"
+			echo "$PROG: $CMD: wirebot could not be started"
 		fi
 		;;
 
 	stop)
 		checkrunning
 
-		if kill $PID; then
-			echo "$PROG: $CMD: wired stopped"
+		if screen -XS wirebot quit; then
+			echo "$PROG: $CMD: wirebot stopped"
 		else
-			echo "$PROG: $CMD: wired could not be stopped"
+			echo "$PROG: $CMD: wirebot could not be stopped"
+			exit 1
+		fi
+		;;
+
+	screen)
+		checkrunning
+
+		if screen -rS wirebot; then
+			echo "$PROG: $CMD: Entering screen session"
+		else
+			echo -e "\n$PROG: $CMD: wirebot is not running"
 			exit 1
 		fi
 		;;
@@ -70,175 +76,49 @@ case $CMD in
 		checkpid
 
 		if [ $RUNNING -eq 1 ]; then
-			if kill $PID; then
-				echo "$PROG: $CMD: wired stopped"
+			if screen -XS wirebot quit; then
+				echo "$PROG: $CMD: wirebot stopped"
 			else
-				echo "$PROG: $CMD: wired could not be stopped"
+				echo "$PROG: $CMD: wirebot could not be stopped"
 				exit 1
 			fi
 		fi
 
-		if $WIRED $WIREDFLAGS; then
-			echo "$PROG: $CMD: wired started"
+		if screen -Sdm wirebot $WIREBOT/wirebot; then
+			echo "$PROG: $CMD: wirebot started"
 		else
-			echo "$PROG: $CMD: wired could not be started"
+			echo "$PROG: $CMD: wirebot could not be started"
 		fi
 		;;
 
-	reload)
-		checkrunning
-
-		if kill -HUP $PID; then
-			echo "$PROG: $CMD: wired reloaded"
-		else
-			echo "$PROG: $CMD: wired could not be reloaded"
-		fi
+	watch)
+		/bin/bash "$HOME/.wirebot/wirebot.sh" watcher_start
 		;;
 
-	register)
-		checkrunning
-
-		if kill -USR1 $PID; then
-			echo "$PROG: $CMD: wired registering with trackers"
-		else
-			echo "$PROG: $CMD: wired could not register with trackers"
-		fi
-		;;
-
-	index)
-		checkrunning
-
-		if kill -USR2 $PID; then
-			echo "$PROG: $CMD: wired indexing"
-		else
-			echo "$PROG: $CMD: wired could not be indexed"
-		fi
-		;;
-
-	clean)
-		checkrunning
-
-		if kill -PROF $PID; then
-			echo "$PROG: $CMD: wired cleaning events"
-		else
-			echo "$PROG: $CMD: wired could not clean events"
-		fi
+	nowatch)
+		/bin/bash "$HOME/.wirebot/wirebot.sh" watcher_stop
 		;;
 
 	config)
 		grep -v "^#" $CONFIGFILE | grep -v "^$" | sort
 		;;
 
-	configtest)
-		$WIRED -t
-		;;
-	
-	debug)
-		echo "run -D $WIREDFLAGS" | gdb $WIRED
-		;;
-
-	status)
-		if [ -f $STATUSFILE ]; then
-			$WIRED -v
-			awk '
-				function pad(number) {
-					if(number < 10)
-						return "0" number
-					else
-						return number
-				}
-
-				function ftime(time) {
-					days = int(time / 86400)
-					time = time % 86400
-
-					hours = int(time / 3600)
-					time = time % 3600
-
-					minutes = int(time / 60)
-					time = time % 60
-
-					seconds = time
-
-					if(days > 0)
-						return pad(days) ":" pad(hours) ":" \
-							   pad(minutes) ":" pad(seconds) \
-							   " days"
-					else if(hours > 0)
-						return pad(hours) ":" pad(minutes) ":" \
-							   pad(seconds) " hours"
-					else if(minutes > 0)
-						return pad(minutes) ":" pad(seconds) \
-							   " minutes"
-					else
-						return seconds " seconds"
-				}
-
-				function fbytes(bytes) {
-					power = 0
-
-					while(bytes > (1024 ^ ++power))
-						;
-
-					value = sprintf("%.2f", bytes / (1024 ^ --power))
-
-					if(power == 4)
-						return value " TB"
-					else if(power == 3)
-						return value " GB"
-					else if(power == 2)
-						return value " MB"
-					else if(power == 1)
-						return value " KB"
-					else if(power == 0)
-						if(bytes == 1)
-							return bytes " byte"
-						else
-							return bytes " bytes"
-				}
-
-				{
-					"date +%s" | getline now
-					print "Up " ftime(now - $1)
-					print ""
-					print "Current users:              " $2
-					print "Total users:                " $3
-					print "Current downloads:          " $4
-					print "Total downloads:            " $5
-					print "Current uploads:            " $6
-					print "Total uploads:              " $7
-					print "Downloads traffic:          " fbytes($8)
-					print "Uploads traffic:            " fbytes($9)
-					print "Total traffic:              " fbytes($8 + $9)
-					print "Current tracker servers:    " $10
-					print "Current tracker users:      " $11
-					print "Current tracker files:      " $12
-					print "Current tracker size:       " fbytes($13)
-				}
-			' $STATUSFILE
-		else
-			echo "$PROG: $CMD: $STATUSFILE could not be found"
-		fi
-		;;
-
 	*)
 		cat <<EOF
-Usage: wiredctl [start | stop | restart | reload | index | register | clean | config | configtest | debug | status | help]
 
-    start        start wired
-    stop         stop wired
-    restart      restart wired
-    reload       send wired a SIGHUP, causing it to reload its configuration
-    index        send wired a SIGUSR1, causing it to re-index the files
-    register     send wired a SIGUSR2, causing it to register with trackers
-    clean        send wired a SIGPROF, causing it to clean server events
-    config       show the configuration
-    configtest   run a configuration syntax test
-    debug        start wired in the debugger
-    status       show a status screen
-    help         show this information
+Usage: wirebotctl [start | stop | restart | watch/nowatch | screen | status | config]
 
-By Rafaël Warnault <dev@read-write.fr>
+	start			start wirebot
+	stop			stop wirebot
+	restart			restart wirebot
+	screen			go into screen session
+	watch/nowatch		Switch filewatching on/off
+	status			show the status
+	config			show the configuration
+    
+By Prof. Dr. Luigi 
+Original by Rafaël Warnault <dev@read-write.fr>
+
 EOF
 		;;
 esac
