Update wirebotctl

diff --git a/wirebotctl b/wirebotctl
--- a/wirebotctl
+++ b/wirebotctl
@@ -13,216 +13,216 @@ PROG=$(basename $0)
 CMD=$1
 
 checkpid() {
-	RUNNING=0
+        RUNNING=0
 
-	if [ -f $PIDFILE ]; then
-		PID=`cat $PIDFILE`
+        if [ -f $PIDFILE ]; then
+                PID=`cat $PIDFILE`
 
-		if [ "x$PID" != "x" ]; then
-			if kill -0 $PID 2>/dev/null ; then
-				RUNNING=1
-			fi
-		fi
-	fi
+                if [ "x$PID" != "x" ]; then
+                        if kill -0 $PID 2>/dev/null ; then
+                                RUNNING=1
+                        fi
+                fi
+        fi
 }
 
 checkrunning() {
-	checkpid
+        checkpid
 
-	if [ $RUNNING -eq 0 ]; then
-		echo "$PROG: $CMD: wirebot is not running"
-		exit 1
-	fi
+        if [ $RUNNING -eq 0 ]; then
+                echo "$PROG: $CMD: wirebot is not running"
+                exit 1
+        fi
 }
 
 case $CMD in
-	start)
-		checkpid
+        start)
+                checkpid
 
-		if [ $RUNNING -eq 1 ]; then
-			echo "$PROG: $CMD: wirebot (pid $PID) already running"
-			exit 1
-		fi
+                if [ $RUNNING -eq 1 ]; then
+                        echo "$PROG: $CMD: wirebot (pid $PID) already running"
+                        exit 1
+                fi
 
-		if screen -Sdm wirebot $WIREBOT/wirebot ; then
-			/bin/bash "$HOME/.wirebot/wirebot.sh" watcher_init
-			#echo "$PROG: $CMD: wirebot started"
-			/bin/bash "$HOME/.wirebot/wirebot.sh" rssfeed_init
-			#echo "RSS feed started"
-		else
-			echo "$PROG: $CMD: wirebot could not be started"
-		fi
-		;;
+                if screen -Sdm wirebot $WIREBOT/wirebot ; then
+                        /bin/bash "$HOME/.wirebot/wirebot.sh" watcher_init
+                        #echo "$PROG: $CMD: wirebot started"
+                        /bin/bash "$HOME/.wirebot/wirebot.sh" rssfeed_init
+                        #echo "RSS feed started"
+                else
+                        echo "$PROG: $CMD: wirebot could not be started"
+                fi
+                ;;
 
-	stop)
-		checkrunning
+        stop)
+                checkrunning
 
-		if screen -XS wirebot quit; then
-			if [ -f "$HOME/.wirebot/watcher.pid" ];then
-			  rm "$HOME/.wirebot/watcher.pid"
-			fi
-			if [ -f "$HOME/.wirebot/wirebot.pid" ];then
-			  rm "$HOME/.wirebot/wirebot.pid"
-			fi
-			if [ -f "$HOME/.wirebot/rss.pid" ];then
-			  rm "$HOME/.wirebot/rss.pid"
-			fi
-			echo "$PROG: $CMD: wirebot stopped"
-		else
-			echo "$PROG: $CMD: wirebot could not be stopped"
-			exit 1
-		fi
-		;;
-	status)
-		checkpid
+                if screen -XS wirebot quit; then
+                        if [ -f "$HOME/.wirebot/watcher.pid" ];then
+                          rm "$HOME/.wirebot/watcher.pid"
+                        fi
+                        if [ -f "$HOME/.wirebot/wirebot.pid" ];then
+                          rm "$HOME/.wirebot/wirebot.pid"
+                        fi
+                        if [ -f "$HOME/.wirebot/rss.pid" ];then
+                          rm "$HOME/.wirebot/rss.pid"
+                        fi
+                        echo "$PROG: $CMD: wirebot stopped"
+                else
+                        echo "$PROG: $CMD: wirebot could not be stopped"
+                        exit 1
+                fi
+                ;;
+        status)
+                checkpid
 
-		if [ $RUNNING -eq 1 ]; then
-			echo ""
-			echo "$PROG: $CMD: wirebot is running on pid $PID"
-			
-			check=$( ps ax | grep -v grep | grep "inotifywait" )
-  				if [ "$check" != "" ] && [ -f "$PIDFILE_WATCHER" ]; then
-					WATCHER_PID=$( cat "$PIDFILE_WATCHER" )
-					echo "$PROG: $CMD: watcher is running on pid $WATCHER_PID"
-				fi
-		fi
+                if [ $RUNNING -eq 1 ]; then
+                        echo ""
+                        echo "$PROG: $CMD: wirebot is running on pid $PID"
 
-		join_check=$( cat "$BASHFILE" | grep -v "sed" | grep "user_join=" | sed 's/.*=//g' )
-		leave_check=$( cat "$BASHFILE" | grep -v "sed" | grep "user_leave=" | sed 's/.*=//g' )
-		wordfilter_check=$( cat "$BASHFILE" | grep -v "sed" | grep "wordfilter=" | sed 's/.*=//g' )
-		common_reply_check=$( cat "$BASHFILE" | grep -v "sed" | grep "common_reply=" | sed 's/.*=//g' )
-		admin_user_check=$( cat "$BASHFILE" | grep -v "sed" | grep "admin_user=" | sed -e 's/.*=//g' -e 's/\"//g' )
-		echo ""
-		echo "Settings:"
-		echo ""
-		echo "User join    =" "$join_check"
-		echo "User leave   =" "$leave_check"
-		echo "Wordfilter   =" "$wordfilter_check"
-		echo "Common reply =" "$common_reply_check"
-		echo "Admin user   =" "$admin_user_check"
-		echo ""
-		;;
+                        check=$( ps ax | grep -v grep | grep "inotifywait" )
+                                if [ "$check" != "" ] && [ -f "$PIDFILE_WATCHER" ]; then
+                                        WATCHER_PID=$( cat "$PIDFILE_WATCHER" )
+                                        echo "$PROG: $CMD: watcher is running on pid $WATCHER_PID"
+                                fi
+                fi
 
-	screen)
-		checkrunning
+                join_check=$( cat "$BASHFILE" | grep -v "sed" | grep "user_join=" | sed 's/.*=//g' )
+                leave_check=$( cat "$BASHFILE" | grep -v "sed" | grep "user_leave=" | sed 's/.*=//g' )
+                wordfilter_check=$( cat "$BASHFILE" | grep -v "sed" | grep "wordfilter=" | sed 's/.*=//g' )
+                common_reply_check=$( cat "$BASHFILE" | grep -v "sed" | grep "common_reply=" | sed 's/.*=//g' )
+                admin_user_check=$( cat "$BASHFILE" | grep -v "sed" | grep "admin_user=" | sed -e 's/.*=//g' -e 's/\"//g' )
+                echo ""
+                echo "Settings:"
+                echo ""
+                echo "User join    =" "$join_check"
+                echo "User leave   =" "$leave_check"
+                echo "Wordfilter   =" "$wordfilter_check"
+                echo "Common reply =" "$common_reply_check"
+                echo "Admin user   =" "$admin_user_check"
+                echo ""
+                ;;
 
-		if screen -rS wirebot -p 0; then
-			echo "$PROG: $CMD: Entering screen session"
-		else
-			echo -e "\n$PROG: $CMD: wirebot is not running"
-			exit 1
-		fi
-		;;
+        screen)
+                checkrunning
 
-	restart)
-		checkpid
+                if screen -rS wirebot -p 0; then
+                        echo "$PROG: $CMD: Entering screen session"
+                else
+                        echo -e "\n$PROG: $CMD: wirebot is not running"
+                        exit 1
+                fi
+                ;;
 
-		if [ $RUNNING -eq 1 ]; then
-			if screen -XS wirebot quit; then
-				if [ -f "$HOME/.wirebot/watcher.pid" ];then
-				  rm "$HOME/.wirebot/watcher.pid"
-				fi
-				if [ -f "$HOME/.wirebot/wirebot.pid" ];then
-				  rm "$HOME/.wirebot/wirebot.pid"
-				fi
-				echo "$PROG: $CMD: wirebot stopped"
-			else
-				echo "$PROG: $CMD: wirebot could not be stopped"
-				exit 1
-			fi
-		fi
+        restart)
+                checkpid
 
-		if screen -Sdm wirebot $WIREBOT/wirebot; then
-			/bin/bash "$HOME/.wirebot/wirebot.sh" watcher_init
-			echo "$PROG: $CMD: wirebot started"
-		else
-			echo "$PROG: $CMD: wirebot could not be started"
-		fi
-		;;
+                if [ $RUNNING -eq 1 ]; then
+                        if screen -XS wirebot quit; then
+                                if [ -f "$HOME/.wirebot/watcher.pid" ];then
+                                  rm "$HOME/.wirebot/watcher.pid"
+                                fi
+                                if [ -f "$HOME/.wirebot/wirebot.pid" ];then
+                                  rm "$HOME/.wirebot/wirebot.pid"
+                                fi
+                                echo "$PROG: $CMD: wirebot stopped"
+                        else
+                                echo "$PROG: $CMD: wirebot could not be stopped"
+                                exit 1
+                        fi
+                fi
 
-	watch)
-		/bin/bash "$BASHFILE" watcher_start
-		;;
+                if screen -Sdm wirebot $WIREBOT/wirebot; then
+                        /bin/bash "$HOME/.wirebot/wirebot.sh" watcher_init
+                        echo "$PROG: $CMD: wirebot started"
+                else
+                        echo "$PROG: $CMD: wirebot could not be started"
+                fi
+                ;;
 
-	nowatch)
-		/bin/bash "$BASHFILE" watcher_stop
-		;;
+        watch)
+                /bin/bash "$BASHFILE" watcher_start
+                ;;
 
-	config)
-		grep -v "^#" $CONFIGFILE | grep -v "^$" | sort
-		;;
-	
-	join_on)
-		/bin/bash "$BASHFILE" user_join_on
-		;;
+        nowatch)
+                /bin/bash "$BASHFILE" watcher_stop
+                ;;
 
-	join_off)
-		/bin/bash "$BASHFILE" user_join_off
-		;;
+        config)
+                grep -v "^#" $CONFIGFILE | grep -v "^$" | sort
+                ;;
 
-	leave_on)
-		/bin/bash "$BASHFILE" user_leave_on
-		;;
+        join_on)
+                /bin/bash "$BASHFILE" user_join_on
+                ;;
 
-	leave_off)
-		/bin/bash "$BASHFILE" user_leave_off
-		;;
+        join_off)
+                /bin/bash "$BASHFILE" user_join_off
+                ;;
 
-	wordfilter_on)
-		/bin/bash "$BASHFILE" wordfilter_on
-		;;
+        leave_on)
+                /bin/bash "$BASHFILE" user_leave_on
+                ;;
 
-	wordfilter_off)
-		/bin/bash "$BASHFILE" wordfilter_off
-		;;
+        leave_off)
+                /bin/bash "$BASHFILE" user_leave_off
+                ;;
 
-	common_reply_on)
-		/bin/bash "$BASHFILE" common_reply_on
-		;;
+        wordfilter_on)
+                /bin/bash "$BASHFILE" wordfilter_on
+                ;;
 
-	common_reply_off)
-		/bin/bash "$BASHFILE" common_reply_off
-		;;
+        wordfilter_off)
+                /bin/bash "$BASHFILE" wordfilter_off
+                ;;
 
-	rssfeed_on)
-		/bin/bash "$BASHFILE" rssfeed_start
-		;;
+        common_reply_on)
+                /bin/bash "$BASHFILE" common_reply_on
+                ;;
 
-	rssfeed_off)
-		/bin/bash "$BASHFILE" rssfeed_stop
-		;;
-	*)
-		cat <<EOF
+        common_reply_off)
+                /bin/bash "$BASHFILE" common_reply_off
+                ;;
+
+        rssfeed_on)
+                /bin/bash "$BASHFILE" rssfeed_start
+                ;;
+
+        rssfeed_off)
+                /bin/bash "$BASHFILE" rssfeed_stop
+                ;;
+        *)
+                cat <<EOF
 
 Usage:  wirebotctl [COMMAND]
 
-	COMMAND:
-	start			Start wirebot
-	stop			Stop wirebot
-	restart			Restart wirebot
-	screen			Join screen session (To exit session press ctrl+a and than d)
-	watch/nowatch		Switch filewatching on/off
-	status			Show the status
-	config			Show the configuration
-	
-	join_on			Activate greeting if user joined server
-	join_off		Deactivate greeting if user joined server
-	
-	leave_on		Activate greeting if user leaved server
-	leave_off		Deactivate greeting if user leaved server
+        COMMAND:
+        start                   Start wirebot
+        stop                    Stop wirebot
+        restart                 Restart wirebot
+        screen                  Join screen session (To exit session press ctrl+a and than d)
+        watch/nowatch           Switch filewatching on/off
+        status                  Show the status
+        config                  Show the configuration
 
-	wordfilter_on		Activate wordfilter
-	wordfilter_off		Deactivate wordfilfter
-	
-	common_reply_on		Activate talkativeness
-	common_reply_off	Deactivate talkativeness	
-	
-	rssfeed_on		Activate RSS Newsfeed
-	rssfeed_off		Deactivate RSS Newsfeed
+        join_on                 Activate greeting if user joined server
+        join_off                Deactivate greeting if user joined server
 
-By Prof. Dr. Luigi 
+        leave_on                Activate greeting if user leaved server
+        leave_off               Deactivate greeting if user leaved server
+
+        wordfilter_on           Activate wordfilter
+        wordfilter_off          Deactivate wordfilfter
+
+        common_reply_on         Activate talkativeness
+        common_reply_off        Deactivate talkativeness
+
+        rssfeed_on              Activate RSS Newsfeed
+        rssfeed_off             Deactivate RSS Newsfeed
+
+By Prof. Dr. Luigi
 Original by Rafaël Warnault <dev@read-write.fr>
 
 EOF
-		;;
+                ;;
 esac
